import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {AntdRegistry} from "@ant-design/nextjs-registry";
import {AntdConfigProvider} from "@/app/AntdConfigProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <AntdRegistry>
        <AntdConfigProvider>
          {children}
        </AntdConfigProvider>
      </AntdRegistry>
      </body>
    </html>
  );
}
